[server]
port=8080

[database]
host="127.0.0.1"
port=3306
username="root"
database="main"
password="pass"

[redis]
host="127.0.0.1"
port=6379
username=""
password="pass"
database=0

[jwt]
secret="changeme"
access_token_exp_days=1
refresh_token_exp_days=365
